
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 03 22:31:54 CST 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int True = 18;
  public static final int Coma = 17;
  public static final int Negacion = 45;
  public static final int Llave_c = 4;
  public static final int T_string = 50;
  public static final int Null = 11;
  public static final int Llave_a = 3;
  public static final int T_char = 49;
  public static final int If = 20;
  public static final int Diferente = 40;
  public static final int Potencia = 33;
  public static final int Default = 27;
  public static final int Comentario = 56;
  public static final int Menor = 37;
  public static final int Else = 21;
  public static final int Character = 55;
  public static final int Break = 26;
  public static final int Error = 59;
  public static final int Asignacion = 5;
  public static final int Corchete_c = 14;
  public static final int Mayor = 38;
  public static final int Corchete_a = 13;
  public static final int T_bool = 48;
  public static final int Return = 7;
  public static final int While = 23;
  public static final int Int = 57;
  public static final int Delimitador = 2;
  public static final int Division = 31;
  public static final int Float = 58;
  public static final int Unario_positivo = 35;
  public static final int Parentesis_c = 16;
  public static final int Unario_negatico = 36;
  public static final int Modulo = 34;
  public static final int Conjuncion = 43;
  public static final int Parentesis_a = 15;
  public static final int EOF = 0;
  public static final int Mayor_igual = 42;
  public static final int error = 1;
  public static final int Disyuncion = 44;
  public static final int Switch = 24;
  public static final int False = 19;
  public static final int Char = 12;
  public static final int T_void = 51;
  public static final int Print = 10;
  public static final int String_to_int = 52;
  public static final int Do = 22;
  public static final int Menor_igual = 41;
  public static final int Case = 25;
  public static final int Dos_puntos = 28;
  public static final int T_int = 46;
  public static final int String = 54;
  public static final int Identificador = 53;
  public static final int Simbolo_input = 9;
  public static final int Input = 8;
  public static final int Resta = 30;
  public static final int Multiplicacion = 32;
  public static final int Suma = 29;
  public static final int T_float = 47;
  public static final int Main = 6;
  public static final int Igual = 39;
}

