
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 06 22:55:58 CST 2020
//----------------------------------------------------

package Codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int True = 17;
  public static final int Coma = 16;
  public static final int Negacion = 44;
  public static final int Llave_c = 4;
  public static final int T_string = 49;
  public static final int Null = 11;
  public static final int Llave_a = 3;
  public static final int T_char = 48;
  public static final int If = 19;
  public static final int Diferente = 39;
  public static final int Potencia = 32;
  public static final int Default = 26;
  public static final int Comentario = 55;
  public static final int Menor = 36;
  public static final int Else = 20;
  public static final int Character = 54;
  public static final int Break = 25;
  public static final int Error = 58;
  public static final int Asignacion = 5;
  public static final int Corchete_c = 13;
  public static final int Mayor = 37;
  public static final int Corchete_a = 12;
  public static final int T_bool = 47;
  public static final int Return = 7;
  public static final int While = 22;
  public static final int Int = 56;
  public static final int Delimitador = 2;
  public static final int Division = 30;
  public static final int Float = 57;
  public static final int Unario_positivo = 34;
  public static final int Parentesis_c = 15;
  public static final int Unario_negatico = 35;
  public static final int Modulo = 33;
  public static final int Conjuncion = 42;
  public static final int Parentesis_a = 14;
  public static final int EOF = 0;
  public static final int Mayor_igual = 41;
  public static final int error = 1;
  public static final int Disyuncion = 43;
  public static final int Switch = 23;
  public static final int False = 18;
  public static final int T_void = 50;
  public static final int Print = 10;
  public static final int String_to_int = 51;
  public static final int Do = 21;
  public static final int Menor_igual = 40;
  public static final int Case = 24;
  public static final int Dos_puntos = 27;
  public static final int T_int = 45;
  public static final int String = 53;
  public static final int Identificador = 52;
  public static final int Simbolo_input = 9;
  public static final int Input = 8;
  public static final int Resta = 29;
  public static final int Multiplicacion = 31;
  public static final int Suma = 28;
  public static final int T_float = 46;
  public static final int Main = 6;
  public static final int Igual = 38;
}

