
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jul 12 19:33:02 CST 2020
//----------------------------------------------------

package Codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int True = 17;
  public static final int Coma = 16;
  public static final int Negacion = 46;
  public static final int Llave_c = 4;
  public static final int T_string = 51;
  public static final int Null = 11;
  public static final int Llave_a = 3;
  public static final int T_char = 50;
  public static final int If = 19;
  public static final int Diferente = 41;
  public static final int Potencia = 34;
  public static final int Default = 27;
  public static final int Menor = 38;
  public static final int Else = 20;
  public static final int Character = 56;
  public static final int Break = 26;
  public static final int Error = 59;
  public static final int Asignacion = 5;
  public static final int Corchete_c = 13;
  public static final int Mayor = 39;
  public static final int Corchete_a = 12;
  public static final int T_bool = 49;
  public static final int Return = 7;
  public static final int While = 22;
  public static final int Int = 57;
  public static final int Delimitador = 2;
  public static final int Division = 32;
  public static final int Float = 58;
  public static final int Unario_positivo = 36;
  public static final int Parentesis_c = 15;
  public static final int Unario_negatico = 37;
  public static final int Modulo = 35;
  public static final int Conjuncion = 44;
  public static final int Parentesis_a = 14;
  public static final int For = 23;
  public static final int EOF = 0;
  public static final int Mayor_igual = 43;
  public static final int error = 1;
  public static final int Disyuncion = 45;
  public static final int Switch = 24;
  public static final int False = 18;
  public static final int T_void = 52;
  public static final int Print = 10;
  public static final int String_to_int = 53;
  public static final int Do = 21;
  public static final int Menor_igual = 42;
  public static final int Case = 25;
  public static final int Dos_puntos = 29;
  public static final int T_int = 47;
  public static final int String = 55;
  public static final int Identificador = 54;
  public static final int Simbolo_input = 9;
  public static final int Input = 8;
  public static final int Resta = 31;
  public static final int Sig_pregunta = 28;
  public static final int Multiplicacion = 33;
  public static final int Suma = 30;
  public static final int T_float = 48;
  public static final int Main = 6;
  public static final int Igual = 40;
}

